Spider/Spider/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^spending/', include('spending.urls')),
    url(r'^admin/', admin.site.urls),
]

Spider/spending/urls.py
'''
Created on 23.09.2017

@author: Adrian
'''

from django.conf.urls import url

from . import views

app_name = 'spend'
urlpatterns = [
    # ex: /spending/
    url(r'^$', views.listPurchases, name='index'),
    # ex: /spending/3/  
    url(r'^(?P<shopping_id>[0-9]+)/$', views.getShoppingById, name='detail'),
    # ex: /spending/5/results/
    url(r'^(?P<shopping_id>[0-9]+)/results/$', views.result, name='results'),
    # ex: /spending/detail/3/
    url(r'^detail/(?P<shopping_id>[0-9]+)/$', views.detail, name='detailnew'),
    # ex: /spending/3/vote/
    url(r'^(?P<shopping_id>[0-9]+)/vote/$', views.vote, name='vote')
]   

Spider/spending/models.py
from django.db import models

class Shopping(models.Model):
    sum = models.DecimalField(max_digits=10, decimal_places=2)
    store_name = models.CharField(max_length=255)
    shop_date = models.DateTimeField('date published')
    
    def __str__(self):
        return 'sum = "%s" store_name = "%s" shop_date= "%s"' % (self.sum.__str__(), self.store_name.__str__(), self.shop_date.__str__())
    
class Article(models.Model):
    Shopping = models.ForeignKey(Shopping, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return 'name = "%s" price = "%s"' % (self.name.__str__(), self.price.__str__()) 

Spider/spending/views.py
from django.http.response import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from .models import Shopping
from django.shortcuts import render, get_object_or_404
from django.urls.base import reverse

# Create your views here.

def index(request):
    latest_shopping_list = Shopping.objects.order_by('-shop_date')[:51]
    template = loader.get_template('spending/index.html')
    context = {
        'latest_shopping_list': latest_shopping_list,
    }
    return HttpResponse(template.render(context, request))

def listPurchases(request):
    latest_shopping_list = Shopping.objects.order_by('-shop_date')[:50]
    template = loader.get_template('spending/listPurchases.html')
    context = {
        'latest_shopping_list': latest_shopping_list,
    }
    return HttpResponse(template.render(context, request))


def getShoppingById(request, shopping_id):
    try:
        shopping = Shopping.objects.get(pk=shopping_id)
        template = loader.get_template('spending/indexTwo.html')
        context = {
            'shopping': shopping,
        }
    except Shopping.DoesNotExist:
        raise Http404("Shopping does not exist")
    return HttpResponse(template.render(context, request))

def detail(request, shopping_id):
    try:
        shopping = Shopping.objects.get(pk=shopping_id)
    except Shopping.DoesNotExist:
        raise Http404("Shopping does not exist")
    return render(request, 'spending/detail.html', {'shopping': shopping})

def result(request, shopping_id):
    latest_shopping_list = Shopping.objects.order_by('-shop_date')[:5]
    template = loader.get_template('spending/index.html')
    context = {
        'latest_shopping_list': latest_shopping_list,
    }
    return HttpResponse(template.render(context, request))

def vote(request, shopping_id):
    shopping = get_object_or_404(Shopping, pk=shopping_id)
    try:
        selected_article = shopping.article_set.get(pk=request.POST['article'])
    except (KeyError, Shopping.DoesNotExist):
        # Redisplay the voting form.
        return render(request, 'spending/detail.html', {
            'shopping': shopping,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_article.price += 1
        selected_article.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('spend:results', args=(shopping.id,)))
    
    
def results(request, shopping_id):
    shopping = get_object_or_404(Shopping, pk=shopping_id)
    return render(request, 'spending/results.html', {'shopping': shopping})

Spider/spending/templates/spending/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	<h1>{{ shopping }}</h1>
	
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	
	<form action="{% url 'spend:vote' shopping.id %}" method="post">
	{% csrf_token %}
	{% for article in shopping.article_set.all %}
		<input type="radio" name="article" id="article{{ forloop.counter }}" value="{{ article.id }}" />
		<label for="article{{ forloop.counter }}">{{ article.name }}</label>
		<br />
	{% endfor %}
	<input type="submit" value="Vote" />
	</form>
</body>
</html>

Spider/spending/templates/spending/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
{% if latest_shopping_list %}
    <ul>
    {% for shopping in latest_shopping_list %}
        <li><a href="{% url 'spend:detail' shopping.id %}">{{ shopping.shop_date }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No shopping are available.</p>
{% endif %}
</body>
</html>

Spider/spending/templates/spending/indexTwo.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
{% if shopping %}
    <ul>
    	<li>Datum: {{ shopping.shop_date  }}, Kosten: {{ shopping.sum  }}, Laden: {{ shopping.store_name }} </li>
    	<ul>
		{% for article in shopping.article_set.all %}
		    <li>{{ article.name }}</li>
		{% endfor %}
		</ul>
    </ul>
{% else %}
    <p>No shopping is available.</p>
{% endif %}
</body>
</html>

Spider/spending/templates/spending/listPurchases.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
	integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
	crossorigin="anonymous">
</head>
<body>
	{% if latest_shopping_list %}
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Datum</th>
				<th scope="col">Geschaeft</th>
				<th scope="col">Bezahlt</th>
			</tr>
		</thead>
		<tbody>
			{% for shopping in latest_shopping_list %}
			<tr onclick="window.location.href = '{% url 'spend:detail' shopping.id %}';">
				<th scope="row">{{ forloop.counter }}</th>
				<td>{{ shopping.shop_date }}</td>
				<td>{{ shopping.store_name }}</td>
				<td>{{ shopping.sum }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<p>No spending are available.</p>
	{% endif %}
</body>
</html>

Spider/spending/templates/spending/results.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	<h1>{{ shopping.store_name }}</h1>

	<ul>
	{% for shopping in shopping.article_set.all %}
	    <li>{{ shopping.store_name }} -- {{ shopping.store_name }} vote{{ shopping.store_name }}</li>
	{% endfor %}
	</ul>
	
	<a href="{% url 'spend:vote' shopping.id %}">Vote again?</a>
</body>
</html>